# Generated by Django 3.0 on 2020-01-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_image', models.ImageField(null=True, upload_to='media/title_image')),
                ('text', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='media/image')),
            ],
        ),
    ]
