# Generated by Django 3.0 on 2020-02-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_artist_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
