# Generated by Django 3.0 on 2020-02-06 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200205_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='image',
        ),
    ]
