# Generated by Django 3.0 on 2020-02-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_artist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='entry',
            field=models.TextField(null=True),
        ),
    ]
