# Generated by Django 3.0 on 2020-02-06 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_artist_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='entry',
        ),
    ]
