# Generated by Django 3.0 on 2020-02-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_artist_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='list_back',
            field=models.ImageField(null=True, upload_to='media/background-image'),
        ),
    ]
