# Generated by Django 3.0 on 2020-02-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_artist_list_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='list_back',
        ),
    ]
