# Generated by Django 3.0 on 2020-02-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('background_image', models.ImageField(null=True, upload_to='media/background-image')),
            ],
        ),
        migrations.DeleteModel(
            name='Background',
        ),
    ]
