# Generated by Django 3.0 on 2020-02-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200215_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
